name: Publish release

on:
  push:
    tags: ['v*']

jobs:
  build:
    name: Build and publish
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PACKAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v2
      - name: Set version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build binaries
        run: make package
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Publish package
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/${{ env.PACKAGE_NAME }}-${{ env.VERSION }}.tar.gz
          asset_name: ${{ env.PACKAGE_NAME }}-${{ env.VERSION }}.tar.gz
          asset_content_type: application/gzip