name: publish

on:
  release:
    types: [created]

jobs:
  terraform_test:
    name: Publish Module
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get release url
        id: get_release_url
        run: |
          set -e
          curl -vfs -L \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref }}
